In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_excel('~/Data/Smartvote/election23/23_ch_nr_candidates_de_2024_03_06.xlsx', index_col=0)
parties = dataset.groupby("party_short").ID_candidate.count().sort_values()
parties

party_short
MCG           24
Lega          40
PdA           79
JEVP          91
Parteilos    141
JSVP         191
JGLP         192
EDU          193
JUSO         222
JFS          225
JG           238
JM           270
EVP          276
Grüne        406
FDP          430
SVP          443
SP           483
Übrige       495
GLP          647
Die Mitte    839
Name: ID_candidate, dtype: int64

In [3]:
party_colors = {
    'EVP': '#FFA500',      # Orange
    'Grüne': '#008000',    # Green
    'FDP': '#0000FF',      # Blue
    'SVP': '#4F7942',      # Slate Gray
    'SP': '#FF0000',       # Red
    'GLP': '#32CD32',      # Lime green
    'Die Mitte': '#C56C46' # Bronze
}

In [4]:
candidates = dataset.loc[dataset['party_short'].isin(party_colors.keys()) & (dataset['canton'] == 1)]
candidates

,ID_user,ID_candidate,ID_election,ID_district,canton,ID_election_party,party_short,ID_district_party,party_REC6,ID_list,...,answer_32264_REC2,answer_32265_REC2,answer_32266_REC2,answer_32267_REC2,answer_32268_REC2,answer_32269_REC2,answer_32270_REC2,answer_32271_REC2,answer_32272_REC2,answer_32273_REC2
16,1783891,58525,1057,952,1,3378,GLP,10694,6,5645,...,100.0,0.0,0.0,100.0,100.0,0.0,100.0,33.0,66.0,100.0
31,1368209,58855,1057,952,1,3372,SP,10563,4,5688,...,0.0,0.0,66.0,100.0,0.0,100.0,33.0,100.0,0.0,0.0
33,515432,56949,1057,952,1,3371,Die Mitte,10537,1,5291,...,100.0,66.0,100.0,33.0,0.0,33.0,33.0,66.0,0.0,0.0
34,1784762,59209,1057,952,1,3371,Die Mitte,10537,1,5708,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,1783899,58559,1057,952,1,3378,GLP,10694,6,5646,...,100.0,66.0,100.0,100.0,0.0,100.0,100.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5908,514065,57015,1057,952,1,3378,GLP,10694,6,5494,...,0.0,66.0,33.0,33.0,0.0,100.0,100.0,66.0,0.0,66.0
5911,513451,59247,1057,952,1,3371,Die Mitte,10537,1,5708,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5915,450931,57621,1057,952,1,3376,SVP,10642,3,5544,...,100.0,33.0,0.0,33.0,66.0,33.0,0.0,33.0,66.0,66.0
5921,515439,56804,1057,952,1,3371,Die Mitte,10537,1,5291,...,33.0,100.0,100.0,66.0,0.0,100.0,33.0,100.0,0.0,0.0
5922,1366823,57914,1057,952,1,3377,Grüne,10668,5,5574,...,0.0,0.0,0.0,100.0,0.0,100.0,0.0,100.0,0.0,0.0

In [5]:
# Use a regex pattern to filter columns
pattern = r'^answer_\d+$'  # ^ and $ ensure no characters before or after the pattern
reactions = candidates.filter(regex=pattern).dropna()/100
reactions

,answer_32214,answer_32215,answer_32216,answer_32217,answer_32218,answer_32219,answer_32220,answer_32221,answer_32222,answer_32223,...,answer_32279,answer_32280,answer_32281,answer_32282,answer_32283,answer_32284,answer_32285,answer_32286,answer_32287,answer_32288
16,0.25,0.75,0.75,0.00,0.75,1.00,0.00,1.00,0.00,1.00,...,0.33,0.83,0.50,0.75,0.75,0.50,0.25,0.75,0.75,0.00
31,0.00,1.00,0.25,0.00,1.00,1.00,0.25,0.25,0.00,0.00,...,0.00,1.00,0.75,1.00,0.25,1.00,0.00,0.50,0.25,0.50
33,0.75,0.25,0.00,0.25,0.00,0.75,1.00,1.00,0.00,0.00,...,0.17,0.83,0.50,1.00,0.50,0.75,0.50,0.50,0.50,0.50
41,0.75,0.75,1.00,0.75,1.00,0.25,0.00,0.25,0.75,0.00,...,0.17,0.83,0.50,0.75,0.00,0.50,0.25,0.50,0.75,0.75
42,0.25,0.75,0.75,0.00,1.00,1.00,0.00,0.25,1.00,0.00,...,0.00,0.83,0.50,0.75,0.50,0.75,0.75,0.50,0.25,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5905,0.00,0.75,1.00,0.75,0.75,0.25,0.00,0.00,0.25,0.25,...,0.33,0.33,0.25,0.75,0.25,0.75,0.50,0.50,0.25,0.25
5908,0.75,0.25,0.00,1.00,0.25,0.00,0.00,0.00,1.00,0.00,...,0.33,0.67,0.25,0.50,0.00,0.50,0.25,0.50,0.25,0.25
5915,0.75,0.00,0.75,0.75,0.00,0.00,0.00,0.00,0.75,0.75,...,0.83,0.00,0.00,0.25,0.75,0.25,0.75,0.75,0.75,0.00
5921,1.00,0.75,0.75,1.00,1.00,0.25,0.00,0.00,0.25,0.00,...,0.17,1.00,0.75,0.75,0.25,0.25,0.50,0.50,0.75,0.50
5922,0.00,1.00,1.00,0.00,1.00,1.00,0.00,1.00,0.00,0.25,...,0.00,1.00,0.75,1.00,0.50,1.00,0.00,0.50,0.00,1.00

In [7]:
reactions.to_csv('../src/data/csv/reactions.csv')

In [8]:
candidates = candidates.loc[reactions.index].filter(['party_short'])
candidates['color'] = candidates.party_short.map(party_colors)
candidates

     party_short    color
16           GLP  #32CD32
31            SP  #FF0000
33     Die Mitte  #C56C46
41           GLP  #32CD32
42     Die Mitte  #C56C46
...          ...      ...
5905   Die Mitte  #C56C46
5908         GLP  #32CD32
5915         SVP  #4F7942
5921   Die Mitte  #C56C46
5922       Grüne  #008000

[572 rows x 2 columns]

In [9]:
candidates.party_short.value_counts()

party_short
GLP          121
SP           104
Die Mitte     94
Grüne         81
SVP           79
EVP           60
FDP           33
Name: count, dtype: int64

In [10]:
candidates.to_csv('../src/data/csv/candidates.csv')